### ISSUE TITLE
Without X_umap in obsm of output adata

### ISSUE THREAD

**Issue by houruiyan** [jsxlei/SCALEX#12]
Hello, I am sorry to bother you again. 
When I finish running SCALEX, I found that adata did not include X_umap in obsm. Is this right? I remember l can directly get X_umap in obsm layer. This is my output adata structure. 
![image](https://user-images.githubusercontent.com/56068158/198223785-d732e2c2-0a8b-449a-b573-5f6f0f4b359f.png)
Something changed? or I remember wrong?

Thank you in advance.
Ruiyan

**Comment by jsxlei** [comment]
Hi Ruiyan, did you have umap.png in your outdir where adata is located? The reason may be because sc.pl.umap was not activated in SCALEX in your case. Here what I am testing is right. The adata should have 
<img width="288" alt="Screen Shot 2022-10-27 at 05 24 50" src="https://user-images.githubusercontent.com/16483537/198283789-d8f6b68a-2f65-4bc0-9fbb-87acada2064f.png">
It would be helpful if you could your command or the way how you run SCALEX.

**Comment by houruiyan** [comment]
Thank you for your reply!

Yes, I have the umap.png in my outdir. Here is my command. 
`nohup SCALEX.py --data_list final_cave.h5ad final_surface.h5ad final_zebrafish.h5ad   --batch_categories cave surface zebrafish  --outdir ./SCALEX_out/ &`

![image](https://user-images.githubusercontent.com/56068158/198425717-c3554a8c-bf1e-4bbd-ad44-a432da0d2420.png)
This is my output file. 

Thank you! 
Ruiyan

**Comment by jsxlei** [comment]
Could you also provide the SCALEX version? It is really wierd that there is no X_umap in adata after plotting the umap.png since it will not be deleted.

**Comment by houruiyan** [comment]
I am sorry for late reply. Now, I think it is ok when I update the SCALEX version by using 
`pip install git+https://github.com/jsxlei/scalex.git` . 

I think the v1.0.0 may produce  the problem that I report. 
Thank you very much for your warm help.
